  CREATE TABLE insertName (
                willhaben_id INTEGER PRIMARY KEY  ,
                platform TEXT,
                summary TEXT,
                property_type TEXT,
                number_of_rooms INTEGER,
                date_published TEXT,
                price INTEGER,
                size_qm INTEGER,
                url TEXT,
                location TEXT,
                description TEXT,
                state TEXT,
                district TEXT,
                seller TEXT,
                estate_size_living_area INTEGER,
                floor TEXT,
                published TEXT,
                country TEXT,
                location_id INTEGER,
                location_quality TEXT,
                address TEXT,
                postcode INTEGER,
                property_type_flat TEXT,
                free_area_type_name TEXT,
                free_area_total INTEGER,
                upselling_ad_searchresult TEXT,
                coordinates TEXT,
                is_private INTEGER
            )